# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-8zQrIQH_FGvCiWNJFPFGgm5csaR_FM
"""

import pandas as pd

titanic=pd.read_csv("/content/Titanic-Dataset.csv")
titanic

titanic.info()

titanic.head()

df=pd.DataFrame(titanic)
df

numerical=[]
binary=[]
nominal=[]

for col in df.columns:
  if(df[col].nunique()==2):
    binary.append(col)
  elif(df[col].dtype=="object"):
    nominal.append(col)
  else:
    numerical.append(col)
df1=pd.DataFrame(numerical,columns=["Numerical"])
df2=pd.DataFrame(binary,columns=["binary"])
df3=pd.DataFrame(nominal,columns=["nominal"])
print(df1)
print()
print(df2)
print()
print(df3)

"""EDA"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print(df.shape)
print(df.columns)
print(df.columns.dtype)
print(df.isnull().sum())
print(df.describe)

"""survival count

"""

sns.countplot(x='Survived',data=titanic)
plt.title("survival count")
plt.show()

sns.countplot(x='Sex',data=titanic)
plt.title("gender")
plt.show()

sns.countplot(x='Pclass',data=titanic)
plt.title("class")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['Age'],bins=20,kde=True)
plt.title("age")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['Fare'],bins=20,kde=True)
plt.title("fare")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='coolwarm')
plt.title("corretation")
plt.show()

num=df.select_dtypes(include=['int64','float64']).columns
print(num)

nominal=['Sex','Embarked']
print(nominal)
binary=['Survived']
print(binary)

gender=df['Sex']
embar=df['Embarked']

count=0
total=0
for s,e in zip(gender,embar):
  if pd.isna(s) or pd.isna(e):
    continue
  total+=1
  if(s!=e):
    count+=1
print(count)
print(total)
print(count/total)

temp=df[['Age','Fare']].dropna()

age=temp.iloc[0]['Age']
fare=temp.iloc[0]['Fare']

age2=temp.iloc[1]['Age']
fare2=temp.iloc[1]['Fare']

print(age,fare)
print(age2,fare2)

manhanttan=abs(age-age2)+abs(fare-fare2)
print(manhanttan)

minkowski=(((age-age2)**3)+((fare-fare2)**3))**(1/3)
print(minkowski)

A=np.array([age,fare])
b=np.array([age2,fare2])
cosine_similarity=np.dot(A,b)/(np.linalg.norm(A)*np.linalg.norm(b))
print(cosine_similarity)

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
df = pd.DataFrame(data)


# print(df.iloc[1])

# print(df.iloc[[0, 2]])


# print(df.iloc[0:2])

print(df.iloc[2, 1])